# Generated by Django 4.1 on 2022-08-25 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_per_hour', models.IntegerField(default=0)),
                ('load_percent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MeaningPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('roads_connected', models.ManyToManyField(to='maps.road')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrawingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.road')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
