# Generated by Django 4.1 on 2022-08-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_drawingpoint_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='road',
            old_name='auto_per_hour',
            new_name='east_to_west_auto_per_hour',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='load_percent',
            new_name='east_to_west_load_percent',
        ),
        migrations.AddField(
            model_name='road',
            name='west_to_east_auto_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='road',
            name='west_to_east_load_percent',
            field=models.IntegerField(default=0),
        ),
    ]
