# Generated by Django 4.1 on 2022-08-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_rename_auto_per_hour_road_east_to_west_auto_per_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawingpoint',
            name='road',
        ),
        migrations.DeleteModel(
            name='MeaningPoint',
        ),
        migrations.AddField(
            model_name='drawingpoint',
            name='road',
            field=models.ManyToManyField(to='maps.road'),
        ),
    ]
