# Generated by Django 4.1 on 2022-08-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_remove_drawingpoint_road_delete_meaningpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='traffic_limit',
            field=models.IntegerField(default=300),
        ),
    ]
