# Generated by Django 4.1 on 2022-08-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_road_traffic_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='east_to_west_auto_per_hour',
        ),
        migrations.RemoveField(
            model_name='road',
            name='east_to_west_load_percent',
        ),
        migrations.RemoveField(
            model_name='road',
            name='west_to_east_auto_per_hour',
        ),
        migrations.RemoveField(
            model_name='road',
            name='west_to_east_load_percent',
        ),
    ]
